### ISSUE TITLE
npm run fault

### ISSUE THREAD

**Issue by azak1r** [revenantal/eve-operations#2]
```
@import "node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss";
^
      File to import not found or unreadable: node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss.
Parent style sheet: stdin
      in /var/www/eve-operations/resources/assets/sass/app.scss (line 7, column 1)
    at runLoaders (/var/www/eve-operations/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/eve-operations/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/var/www/eve-operations/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/var/www/eve-operations/node_modules/async/dist/async.js:958:16)
    at options.error (/var/www/eve-operations/node_modules/node-sass/lib/index.js:294:32)

             Asset       Size  Chunks                    Chunk Names
        /js/app.js     331 kB       0  [emitted]  [big]  /js/app
  /js/flatpickr.js    46.7 kB       1  [emitted]         /js/flatpickr
 /js/operations.js    3.32 kB       2  [emitted]         /js/operations
       /js/home.js  642 bytes       3  [emitted]         /js/home
/css/flatpickr.css      17 kB          [emitted]

ERROR in ./node_modules/css-loader?{"url":true,"sourceMap":false,"importLoaders":1}!./node_modules/postcss-loader/lib?{"sourceMap":true,"ident":"postcss","plugins":[null]}!./node_modules/resolve-url-loader?{"sourceMap":true,"root":"/var/www/eve-operations/node_modules"}!./node_modules/sass-loader/lib/loader.js?{"precision":8,"outputStyle":"expanded","sourceMap":true}!./resources/assets/sass/app.scss
Module build failed:
@import "node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss";
^
      File to import not found or unreadable: node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss.
Parent style sheet: stdin
      in /var/www/eve-operations/resources/assets/sass/app.scss (line 7, column 1)
 @ ./resources/assets/sass/app.scss 4:14-266
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss

ERROR in ./resources/assets/sass/app.scss
Module build failed: ModuleBuildError: Module build failed:
@import "node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss";
^
      File to import not found or unreadable: node_modules/@fortawesome/fontawesome-pro-webfonts/scss/fontawesome.scss.
Parent style sheet: stdin
      in /var/www/eve-operations/resources/assets/sass/app.scss (line 7, column 1)
    at runLoaders (/var/www/eve-operations/node_modules/webpack/lib/NormalModule.js:195:19)
    at /var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:364:11
    at /var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:230:18
    at context.callback (/var/www/eve-operations/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at Object.asyncSassJobQueue.push [as callback] (/var/www/eve-operations/node_modules/sass-loader/lib/loader.js:55:13)
    at Object.<anonymous> (/var/www/eve-operations/node_modules/async/dist/async.js:2257:31)
    at Object.callback (/var/www/eve-operations/node_modules/async/dist/async.js:958:16)
    at options.error (/var/www/eve-operations/node_modules/node-sass/lib/index.js:294:32)
 @ ./resources/assets/sass/app.scss
 @ multi ./resources/assets/js/app.js ./resources/assets/sass/app.scss
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the @ production script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-01-09T17_33_48_391Z-debug.log
```

**Comment by azak1r** [comment]
issue sorted

**Comment by Revenantal** [comment]
To expand, was caused by the inclusion of fortawesome/fontawesome-pro-webfonts which is a paid plugin. Added the auth token as supplied by font awesome which resolved the issue.

**Comment by azak1r** [comment]
maybe future idea, remove  any paid plugins or  make them  optional  so this doesn't  happen again?
